import antfu from '@antfu/eslint-config'

export default antfu({
  type: 'lib',
  typescript: true,
  react: true,
  ignores: [
    '**/dist/**',
    '**/node_modules/**',
    '**/.astro/**',
    '**/.wrangler/**',
    '**/drizzle/**',
    '**/.factory/**',
    '**/.claude/**',
    '**/.github/**',
    '**/.husky/**',
  ],
  rules: {
    // 自定义规则
    'no-console': 'warn',
    '@typescript-eslint/no-unused-vars': 'warn',
    // 降低样式规则级别
    'jsonc/sort-keys': 'off',
    'yaml/quotes': 'off',
    'toml/array-bracket-spacing': 'off',
    'toml/spaced-comment': 'off',
    'perfectionist/sort-named-imports': 'off',
    'style/comma-dangle': 'off',
    'style/member-delimiter-style': 'off',
    'style/brace-style': 'off',
    'style/arrow-parens': 'off',
    'style/semi': 'off',
    'style/indent': 'off',
    'style/eol-last': 'off',
    'style/no-multi-spaces': 'off',
    'style/multiline-ternary': 'off',
    'style/quote-props': 'off',
    'style/no-tabs': 'off',
    'style/spaced-comment': 'off',
    'style/jsx-wrap-multilines': 'off',
    'style/jsx-one-expression-per-line': 'off',
    'style/operator-linebreak': 'off',
    'style/indent-binary-ops': 'off',
    'jsonc/indent': 'off',
    'perfectionist/sort-imports': 'off',
    'unused-imports/no-unused-vars': 'off',
    'ts/no-use-before-define': 'off',
    'toml/key-spacing': 'off',
    'antfu/top-level-function': 'off',
    'antfu/if-newline': 'off',
    'prefer-template': 'off',
    'unicorn/prefer-number-properties': 'off',
    'unused-imports/no-unused-imports': 'warn',
    'import/newline-after-import': 'off',
    'test/prefer-lowercase-title': 'off',
    // TypeScript 规则调整
    'ts/explicit-function-return-type': 'off',
    'ts/consistent-type-imports': 'off',
    'ts/consistent-type-definitions': 'off',
    // React 规则调整
    'react-hooks-extra/no-direct-set-state-in-use-effect': 'off',
    'react/no-array-index-key': 'warn',
    'react-dom/no-missing-button-type': 'warn',
  },
})
