/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9b87190059d36ee0dab0624d1df3afa1)
interface __BaseEnv_Env {
	DB: D1Database;
	MAX_EMAIL_BYTES: 1500000;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_EMAIL_BYTES">> {}
}
