// Generated by Wrangler by running `wrangler types`

interface Env {
	TURNSTILE_SECRET: "0x4AAAAAAAwm3l5MMbA-oRx-rbEkWupD_j4";
	TURNSTILE_SITE_KEY: "0x4AAAAAAAwm3oDFAyipG4dr";
	MAIL_DOMAIN: "what-the-fuck.sbs";
	COOKIE_EXPIRES_IN_SECONDS: 86400;
	DB: D1Database;
}
